name: Build Documentation

on: [push]
jobs:

  build_documentation:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
      - name: install dependencies
        run: pip install -r ./docs/requirements.txt
      - name: build documentation
        run: sphinx-build ./docs ./docs/_build
      - name: Commit files # commit the output folder
        run: |
          git config --local user.email "TrisNol@users.noreply.github.com"
          git config --local user.name "TrisNol GitHub Action"
          git add ./docs
          git commit -m "Add Sphinx documentation via Action"
          git push